### ISSUE TITLE
Warning: Calling bottle :unneeded is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by jhult** [cue-lang/homebrew-tap#1]
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the cue-lang/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/cue-lang/homebrew-tap/cue.rb:9
```

**Comment by myitcv** [comment]
Thanks for raising @jhult. 

@docwhat - thanks for pointing that out. So my assumption is that this warning should disappear if we upgrade GoReleaser. I have just raised https://review.gerrithub.io/c/cue-lang/cue/+/526442 to do just that.

**Comment by docwhat** [comment]
Yup. Also, you can fix it by hand notes and not worry since the next release will use the update.
